# Generated by Django 5.0.4 on 2024-05-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videototext', '0004_keywords_delete_persona_archivo_resumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='C:\\Users\\Zero\\PycharmProjects\\djangoVideoToText\\media'),
        ),
    ]
