# Generated by Django 5.0.4 on 2024-05-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videototext', '0005_alter_archivo_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='transcrition',
            new_name='transcription',
        ),
    ]
