# Generated by Django 5.0.4 on 2024-05-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videototext', '0006_rename_transcrition_archivo_transcription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='keywords',
        ),
        migrations.AddField(
            model_name='archivo',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='videototext.keywords'),
        ),
    ]
