# Generated by Django 5.0.4 on 2024-05-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videototext', '0007_remove_archivo_keywords_archivo_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
